### ISSUE TITLE
Showing Taco3d plot results in exception in ska3 2022.2

### ISSUE THREAD

**Issue by taldcroft** [sot/acis_taco#22]
Using ska3 2022.2rc6, after clicking the `Taco3d` button and changing the timeline slider, I see this error message:
```
cheru% esaview.py FEB2122
Reading /proj/sot/ska3/test/data/acis_taco/FEB2122.pkl
Exception in Tkinter callback
Traceback (most recent call last):
  File "/proj/sot/ska3/test/lib/python3.8/tkinter/__init__.py", line 1892, in __call__
    return self.func(*args)
  File "/proj/sot/ska3/test/bin/esaview.py", line 191, in open_window
    self.canvas.show()
AttributeError: 'FigureCanvasTkAgg' object has no attribute 'show'
```

**Comment by javierggt** [comment]
Googling this, it seems replacing `show` by `draw` might work... I still don't know what changed.

**Comment by javierggt** [comment]
I just checked, and FigureCanvasTkAgg does not have a show method, so does this even work in the current ska3-flight?

**Comment by taldcroft** [comment]
Just checked, and no it does not work in current ska3-flight 2021.15. We really need a list of "by-hand checks" that we do for each release. It definitely did work in the past...
